/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs.new'
import { Route as AuthenticatedCandidatesCandidateIdAnalysisRouteImport } from './routes/_authenticated/candidates.$candidateId.analysis'
import { Route as AuthenticatedCandidatesCandidateIdInterviewRouteImport } from './routes/_authenticated/candidates.$candidateId.interview'
import { Route as AuthenticatedJobsJobIdCandidatesNewRouteImport } from './routes/_authenticated/jobs.$jobId.candidates.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesCandidateIdAnalysisRoute =
  AuthenticatedCandidatesCandidateIdAnalysisRouteImport.update({
    id: '/candidates/$candidateId/analysis',
    path: '/candidates/$candidateId/analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesCandidateIdInterviewRoute =
  AuthenticatedCandidatesCandidateIdInterviewRouteImport.update({
    id: '/candidates/$candidateId/interview',
    path: '/candidates/$candidateId/interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdCandidatesNewRoute =
  AuthenticatedJobsJobIdCandidatesNewRouteImport.update({
    id: '/jobs/$jobId/candidates/new',
    path: '/jobs/$jobId/candidates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/candidates/$candidateId/analysis': typeof AuthenticatedCandidatesCandidateIdAnalysisRoute
  '/candidates/$candidateId/interview': typeof AuthenticatedCandidatesCandidateIdInterviewRoute
  '/jobs/$jobId/candidates/new': typeof AuthenticatedJobsJobIdCandidatesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/candidates/$candidateId/analysis': typeof AuthenticatedCandidatesCandidateIdAnalysisRoute
  '/candidates/$candidateId/interview': typeof AuthenticatedCandidatesCandidateIdInterviewRoute
  '/jobs/$jobId/candidates/new': typeof AuthenticatedJobsJobIdCandidatesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/candidates/$candidateId/analysis': typeof AuthenticatedCandidatesCandidateIdAnalysisRoute
  '/_authenticated/candidates/$candidateId/interview': typeof AuthenticatedCandidatesCandidateIdInterviewRoute
  '/_authenticated/jobs/$jobId/candidates/new': typeof AuthenticatedJobsJobIdCandidatesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jobs/new'
    | '/candidates/$candidateId/analysis'
    | '/candidates/$candidateId/interview'
    | '/jobs/$jobId/candidates/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/jobs/new'
    | '/candidates/$candidateId/analysis'
    | '/candidates/$candidateId/interview'
    | '/jobs/$jobId/candidates/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/jobs/new'
    | '/_authenticated/candidates/$candidateId/analysis'
    | '/_authenticated/candidates/$candidateId/interview'
    | '/_authenticated/jobs/$jobId/candidates/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/$candidateId/analysis': {
      id: '/_authenticated/candidates/$candidateId/analysis'
      path: '/candidates/$candidateId/analysis'
      fullPath: '/candidates/$candidateId/analysis'
      preLoaderRoute: typeof AuthenticatedCandidatesCandidateIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/$candidateId/interview': {
      id: '/_authenticated/candidates/$candidateId/interview'
      path: '/candidates/$candidateId/interview'
      fullPath: '/candidates/$candidateId/interview'
      preLoaderRoute: typeof AuthenticatedCandidatesCandidateIdInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/candidates/new': {
      id: '/_authenticated/jobs/$jobId/candidates/new'
      path: '/jobs/$jobId/candidates/new'
      fullPath: '/jobs/$jobId/candidates/new'
      preLoaderRoute: typeof AuthenticatedJobsJobIdCandidatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedCandidatesCandidateIdAnalysisRoute: typeof AuthenticatedCandidatesCandidateIdAnalysisRoute
  AuthenticatedCandidatesCandidateIdInterviewRoute: typeof AuthenticatedCandidatesCandidateIdInterviewRoute
  AuthenticatedJobsJobIdCandidatesNewRoute: typeof AuthenticatedJobsJobIdCandidatesNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedCandidatesCandidateIdAnalysisRoute:
    AuthenticatedCandidatesCandidateIdAnalysisRoute,
  AuthenticatedCandidatesCandidateIdInterviewRoute:
    AuthenticatedCandidatesCandidateIdInterviewRoute,
  AuthenticatedJobsJobIdCandidatesNewRoute:
    AuthenticatedJobsJobIdCandidatesNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
