/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssessmentsIndexRouteImport } from './routes/_authenticated/assessments.index'
import { Route as AuthenticatedAssessmentsNewRouteImport } from './routes/_authenticated/assessments.new'
import { Route as AuthenticatedEvaluationsIndexRouteImport } from './routes/_authenticated/evaluations.index'
import { Route as AuthenticatedEvaluationsIdRouteImport } from './routes/_authenticated/evaluations.$id'
import { Route as AuthenticatedSubmissionsNewRouteImport } from './routes/_authenticated/submissions.new'
import { Route as AuthenticatedAssessmentsIdIndexRouteImport } from './routes/_authenticated/assessments.$id.index'
import { Route as AuthenticatedAssessmentsIdSpecRouteImport } from './routes/_authenticated/assessments.$id.spec'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsIndexRoute =
  AuthenticatedAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsNewRoute =
  AuthenticatedAssessmentsNewRouteImport.update({
    id: '/assessments/new',
    path: '/assessments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluationsIndexRoute =
  AuthenticatedEvaluationsIndexRouteImport.update({
    id: '/evaluations/',
    path: '/evaluations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluationsIdRoute =
  AuthenticatedEvaluationsIdRouteImport.update({
    id: '/evaluations/$id',
    path: '/evaluations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsNewRoute =
  AuthenticatedSubmissionsNewRouteImport.update({
    id: '/submissions/new',
    path: '/submissions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsIdIndexRoute =
  AuthenticatedAssessmentsIdIndexRouteImport.update({
    id: '/assessments/$id/',
    path: '/assessments/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsIdSpecRoute =
  AuthenticatedAssessmentsIdSpecRouteImport.update({
    id: '/assessments/$id/spec',
    path: '/assessments/$id/spec',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/evaluations/$id': typeof AuthenticatedEvaluationsIdRoute
  '/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/evaluations/': typeof AuthenticatedEvaluationsIndexRoute
  '/assessments/$id/spec': typeof AuthenticatedAssessmentsIdSpecRoute
  '/assessments/$id/': typeof AuthenticatedAssessmentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/evaluations/$id': typeof AuthenticatedEvaluationsIdRoute
  '/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/evaluations': typeof AuthenticatedEvaluationsIndexRoute
  '/assessments/$id/spec': typeof AuthenticatedAssessmentsIdSpecRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/_authenticated/evaluations/$id': typeof AuthenticatedEvaluationsIdRoute
  '/_authenticated/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/_authenticated/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/_authenticated/evaluations/': typeof AuthenticatedEvaluationsIndexRoute
  '/_authenticated/assessments/$id/spec': typeof AuthenticatedAssessmentsIdSpecRoute
  '/_authenticated/assessments/$id/': typeof AuthenticatedAssessmentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/assessments/new'
    | '/evaluations/$id'
    | '/submissions/new'
    | '/assessments/'
    | '/evaluations/'
    | '/assessments/$id/spec'
    | '/assessments/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/assessments/new'
    | '/evaluations/$id'
    | '/submissions/new'
    | '/assessments'
    | '/evaluations'
    | '/assessments/$id/spec'
    | '/assessments/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/candidates'
    | '/_authenticated/dashboard'
    | '/_authenticated/assessments/new'
    | '/_authenticated/evaluations/$id'
    | '/_authenticated/submissions/new'
    | '/_authenticated/assessments/'
    | '/_authenticated/evaluations/'
    | '/_authenticated/assessments/$id/spec'
    | '/_authenticated/assessments/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/': {
      id: '/_authenticated/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthenticatedAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/new': {
      id: '/_authenticated/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AuthenticatedAssessmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations/': {
      id: '/_authenticated/evaluations/'
      path: '/evaluations'
      fullPath: '/evaluations/'
      preLoaderRoute: typeof AuthenticatedEvaluationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations/$id': {
      id: '/_authenticated/evaluations/$id'
      path: '/evaluations/$id'
      fullPath: '/evaluations/$id'
      preLoaderRoute: typeof AuthenticatedEvaluationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/new': {
      id: '/_authenticated/submissions/new'
      path: '/submissions/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof AuthenticatedSubmissionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$id/': {
      id: '/_authenticated/assessments/$id/'
      path: '/assessments/$id'
      fullPath: '/assessments/$id/'
      preLoaderRoute: typeof AuthenticatedAssessmentsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$id/spec': {
      id: '/_authenticated/assessments/$id/spec'
      path: '/assessments/$id/spec'
      fullPath: '/assessments/$id/spec'
      preLoaderRoute: typeof AuthenticatedAssessmentsIdSpecRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAssessmentsNewRoute: typeof AuthenticatedAssessmentsNewRoute
  AuthenticatedEvaluationsIdRoute: typeof AuthenticatedEvaluationsIdRoute
  AuthenticatedSubmissionsNewRoute: typeof AuthenticatedSubmissionsNewRoute
  AuthenticatedAssessmentsIndexRoute: typeof AuthenticatedAssessmentsIndexRoute
  AuthenticatedEvaluationsIndexRoute: typeof AuthenticatedEvaluationsIndexRoute
  AuthenticatedAssessmentsIdSpecRoute: typeof AuthenticatedAssessmentsIdSpecRoute
  AuthenticatedAssessmentsIdIndexRoute: typeof AuthenticatedAssessmentsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAssessmentsNewRoute: AuthenticatedAssessmentsNewRoute,
  AuthenticatedEvaluationsIdRoute: AuthenticatedEvaluationsIdRoute,
  AuthenticatedSubmissionsNewRoute: AuthenticatedSubmissionsNewRoute,
  AuthenticatedAssessmentsIndexRoute: AuthenticatedAssessmentsIndexRoute,
  AuthenticatedEvaluationsIndexRoute: AuthenticatedEvaluationsIndexRoute,
  AuthenticatedAssessmentsIdSpecRoute: AuthenticatedAssessmentsIdSpecRoute,
  AuthenticatedAssessmentsIdIndexRoute: AuthenticatedAssessmentsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
